inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "Gemfile"
    - "*.gemspec"
    - "spec/spec_helper.rb"
    - "config/**/*"
  UseCache: false
Style/Documentation:
  Exclude:
    - "lib/**/*"
    - "spec/faker/bot/*"
Metrics/ModuleLength:
  Enabled: false
